name: Pull request tests
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Test linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile
      - name: Test lint
        run: |
          pnpm lint
      - name: Test prettier
        run: |
          pnpm prettier
